### ISSUE TITLE
avoid parsing of expression in closure expecting attributes

### ISSUE THREAD

**Issue by ModProg** [Kyuuhachi/syn_derive#3]
These require `syn.features = ["full"]` but AFAICT it would be possible to just accept any tokens?

Maybe I'm overlooking something thought.

**Comment by Kyuuhachi** [comment]
It only has `full` as a dev-dependency; when compiling as a library only `parsing` and `derive` are used. If that's not what you're referring to, would you mind clarifying the question?

**Comment by ModProg** [comment]
Well, syn doesn't support, e.g., `#[parse(peek_func = |p| ...)]` without the `full` feature.

**Comment by Kyuuhachi** [comment]
I still don't know what you're talking about. `syn::Expr` requires `full` or `derive`. Could you explain what the actual issue is here?

**Comment by ModProg** [comment]
```rs
#[derive(syn_derive::Parse)]
enum Test {
    #[parse(peek_func = |ps| ps.peek(syn::Token![for]) && ps.peek2(syn::Token![if]))]
    Test(syn::Ident),
}
```
Yields this error when compiling:
```
❯ cargo check
    Checking syn_derive_test v0.1.0
error: unsupported expression; enable syn's features=["full"]
 --> src/main.rs:7:25
  |
7 |     #[parse(peek_func = |ps| ps.peek(syn::Token![for]) && ps.peek2(syn::Token![if]))]
  |                         ^
```

**Comment by ModProg** [comment]
(It is also not enought to add `syn` with `full` oneself):
```toml
[package]
name = "syn_derive_test"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.38", features = ["full"] }
syn_derive = "0.1.7"
```
still yields the same error
